### PR TITLE
Clean urls in urlgen

### PR DESCRIPTION
**Pull request by maxwellmg**
**Story in the Larger Framework**
 - Epic -> Data Reliability -> Decrease Human Intervention -> URL Gen

**Before this code**
 - User would locally, manually run urlgen or copy the sitemap.xml (where applicable)
 - User would then carry urls over to Excel and filter out all non-usable links
 - List generated from this process would then be fed to scrapy

**Aim of Story**
 - Introduce logic which takes user out of the ETL process
 
**What was Accomplished**
 - one_off.py, which contains a program for each streaming service we scrape. Each py takes a single "url" as an argument and returns a clean title url (if there is one to return). If there is no title associated with the url available given, each program returns None
 - The programs for the sitemap streaming sites (dazn, disney, hulu, peacock) were edited. Now when run, each program pulls down a fresh online map from the provided url (in some cases, several urls), cleans them, and returns an output file.
 
**Next Steps**
 - apply export code to the sitemap site programs to send cleaned url lists to s3
 - apply cleaner programs to netflix, hbomax, and appletv urlgens so that links may be extracted, transformed, and then loaded to s3 automatically

### CODE REVIEW

**Comment by gcunruh** [comment]
Can all of the one_off logic be written so the first if contains the positive logic then elif if needed then all else None? Like the way you did netflix. Not all are like this.

**Comment by gcunruh** [comment]
I think we need to separate concerns here. Can you please return the crawler code to just return a list of all urls? We will edit the crawler code to also just return a list... then we will write a script to run each in secession, clean the list using the repeatable functions, and send off to s3. 

1A. Get URLS from crawler return list of urls
1B. Get URLS from sitemaps return list of urls
2. Clean URLS
3. Send to S3

Run this process in succession for each platform. 

Right now - Focus on generating list of urls from sitemap... and separately, working repeatable functions to clean a url given or return None. Functions all seem to work OK, just need to simplify logic per first comment (DAZN too).

**Comment by gcunruh** [comment]
Is the hulu one-off written for the crawler or for the sitemaps?

**Comment by maxwellmg** [comment]
1. I fixed DAZN. That was easy enough. With hulu I think the way I wrote it makes the most sense even though it follows a different pattern. Can explain in comments but would be easier to show on a call. 

2. I am a tad confused when it comes to your second comment as far as exactly how you'd like me to transform the programs as they stand to what you're looking for. Perhaps we can discuss this on a call as well.

3. The hulu one-off is mostly written to receive a url from the sitemap. It doesn't contain discriminating code, meaning if you feed it a non-title hulu url, it wont find fault with it.

**Pull request merged**
